Write-Host "AutoCare Pro - Azure Setup for New Account" -ForegroundColor Cyan
Write-Host "Make sure you have run 'az login' before running this script.`n" -ForegroundColor Yellow

$RG_NAME = "autocare-pro-rg"
$LOCATION = "southeastasia"
$ENV_NAME = "autocare-env"

# 1. Create Resource Group
Write-Host "[1/4] Creating Resource Group ($RG_NAME)..." -ForegroundColor Cyan
az group create --name $RG_NAME --location $LOCATION | Out-Null

# 2. Create Container App Environment
Write-Host "[2/4] Creating Container App Environment ($ENV_NAME)... This takes 1-2 minutes." -ForegroundColor Cyan
# This command automatically creates a Log Analytics workspace behind the scenes
az containerapp env create --name $ENV_NAME --resource-group $RG_NAME --location $LOCATION | Out-Null

# Secrets to be used across apps
$DB_URL = "postgresql://postgres.qtpnbjemcjdiidcgetui:Octagony4s25332@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres"
$JWT = "autocare-super-secret-jwt-2026-sliit"

# 3. Create Apps (with the correct target ports!)
Write-Host "[3/4] Creating Backend Microservices (Port 3000)..." -ForegroundColor Cyan

az containerapp create --name customer-vehicle --resource-group $RG_NAME --environment $ENV_NAME `
    --image rachcha/autocare-customer-vehicle:latest --target-port 3000 --ingress external `
    --env-vars DATABASE_URL="${DB_URL}?search_path=cv" JWT_SECRET="$JWT" PORT="3000" | Out-Null

az containerapp create --name appointment --resource-group $RG_NAME --environment $ENV_NAME `
    --image rachcha/autocare-appointment:latest --target-port 3001 --ingress external `
    --env-vars DATABASE_URL="${DB_URL}?search_path=appointment" JWT_SECRET="$JWT" PORT="3001" | Out-Null

az containerapp create --name job --resource-group $RG_NAME --environment $ENV_NAME `
    --image rachcha/autocare-job:latest --target-port 3002 --ingress external `
    --env-vars DATABASE_URL="${DB_URL}?search_path=job" JWT_SECRET="$JWT" PORT="3002" | Out-Null

az containerapp create --name payment --resource-group $RG_NAME --environment $ENV_NAME `
    --image rachcha/autocare-payment:latest --target-port 3003 --ingress external `
    --env-vars DATABASE_URL="${DB_URL}?search_path=payment" JWT_SECRET="$JWT" PORT="3003" | Out-Null

Write-Host "[4/4] Creating Gateway and Frontend (Port 80)..." -ForegroundColor Cyan

az containerapp create --name gateway --resource-group $RG_NAME --environment $ENV_NAME `
    --image rachcha/autocare-gateway:latest --target-port 80 --ingress external `
    --env-vars PORT="80" | Out-Null

az containerapp create --name frontend --resource-group $RG_NAME --environment $ENV_NAME `
    --image rachcha/autocare-frontend:latest --target-port 80 --ingress external | Out-Null


# Retrieve the new Base URL Suffix generated by Azure
$FrontendUrl = az containerapp show --name frontend --resource-group $RG_NAME --query properties.configuration.ingress.fqdn -o tsv
$NewSuffix = $FrontendUrl.Replace("frontend.", "")

Write-Host "`n=======================================================" -ForegroundColor Green
Write-Host "✅ Azure Infrastructure Created Successfully!" -ForegroundColor Green
Write-Host "=======================================================" -ForegroundColor Green
Write-Host "`nIMPORTANT NEXT STEP:" -ForegroundColor Yellow
Write-Host "Your new Azure Environment has a different DNS suffix."
Write-Host "Go to your deploy-azure.ps1 file and change line 6 to:"
Write-Host "`$Suffix = `"$NewSuffix`"" -ForegroundColor Cyan
Write-Host "`nAfter updating the suffix, run '.\deploy-azure.ps1' to correctly cross-link the environment variables." -ForegroundColor Yellow
