sonar.projectKey=autocare-pro_customer-vehicle-service
sonar.projectName=AutoCare Pro - Customer Vehicle Service
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
